<?php


function islandora_map_browse_init(){
    drupal_add_css(drupal_get_path('module', 'islandora_map_browse') .'/css/popup.css');
}

/*
function islandora_map_browse_menu(){
	$items['islandora/map/browse'] = array(
    'title' => 'Browse repository by map',
    'description' => 'View collection map',
    'page callback' => 'browse_collection',
    'file' => 'includes/islandora_browse.inc',
    'access arguments' => array('view fedora collection'),
    'type' => MENU_NORMAL_ITEM,
    );

	 return $items;
}
*/

/**
 * Implements hook_islandora_solr_secondary_display()
 */
function islandora_map_browse_islandora_solr_secondary_display() {
  // set path
  global $base_path;
  $path = $base_path . drupal_get_path('module', 'islandora_map_browse');
  return array(
    'MapView' => array(
      'name' => t('Map View'),
      'module' => 'islandora_map_browse',
      'file' => 'includes/IslandoraSolrResultsMapView.inc',
      'class' => 'IslandoraSolrResultsMapView',
      'function' => 'mapResults',
      'description' => 'Display Results on a Map',
      'logo' => '<img src="' . $path . '/images/map-icon-96.png" class="islandora_solr_secondary_display_icon">',
    ),
    'MapPageView' => array(
      'name' => t('Map Page View'),
      'module' => 'islandora_map_browse',
      'file' => 'includes/IslandoraSolrResultsMapView.inc',
      'class' => 'IslandoraSolrResultsMapView',
      'function' => 'mapPageResults',
      'description' => 'Display Single Page Results on a Map',
      'logo' => '<img src="' . $path . '/images/map-icon-72.png" class="islandora_solr_secondary_display_icon">',
    ),
  );
}


